### ISSUE TITLE
Sidebar display issue

### ISSUE THREAD

**Issue by mubaidr** [cristijora/vue-paper-dashboard#2]
Sidebar is buggy when window width is between 766px and 990px

**Comment by cristijora** [comment]
Can you provide some more details? Screenshot, operating system, browser ?

**Comment by mubaidr** [comment]
Windows 10
Opera 44

![capture](https://cloud.githubusercontent.com/assets/2222702/25861321/3d3a2d5e-3499-11e7-9c1f-97dc2ebfd68b.PNG)

**Comment by cristijora** [comment]
Please make sure the issue is present with the code from the master branch. I pulled in your changes and the whole UI seems totally different because of this:
```js
import App from './App'
// router setup
import routes from './routes/routes'
// vuex store
import store from './vuex/store'
// library imports
import Chartist from 'chartist'
import 'bootstrap/dist/css/bootstrap.css'
import 'es6-promise/auto'
```
You moved the `App` import before the bootstrap import which is essential for the whole thing to work and look properly. Make sure app is imported after all the library imports
```
// library imports
import Chartist from 'chartist'
import 'bootstrap/dist/css/bootstrap.css'
import 'es6-promise/auto'
//other code
//import app only here
import App from './App'
```
Again Please make sure an issue is present with the code from the current master branch so we avoid spending time on such stuff!
