### ISSUE TITLE
Could you help me understand this line about plugins?

### ISSUE THREAD

**Issue by fakefarm** [cristijora/vue-paper-dashboard#22]
Hello, 
First off, thank you for writing this incredible app! It is well written and gives me a great understanding of how to write complex apps. I am new to Vue and doing my best to understand how all these fancy concepts work.I wrote a question on [an old commit](https://github.com/cristijora/vue-paper-dashboard/commit/e8f006c4d87fa331a52ffd494e833d350146fb35#commitcomment-25663748) and wonder if you'd be willing to share some insight. 

Also, I noticed you removed vuex but I couldn't find the commit which you did that. Was there any specific reason or just found it to be unnecessary?

Thanks again!

**Comment by cristijora** [comment]
Hi there. Glad it helps you to learn faster.
Usually  components are suited for most cases. I would say 80-90% of the cases.
For the rest 10-20%, you might find yourself using directives and plugins.
Plugins usually incorporate some logic (data, component registration, maybe mixins or even directives)

Regarding your comment, a mixin was used there to make use of reactivity on the `sidebarStore` 
If I were to declare `Vue.prototype.$sidebar = sidebarStore` this would've worked fine and indeed is more simple but has one caveat. If you declare it like this, it means that the `$sidebar` property will not be reactive. This is fine if you have methods on it but in this case there is a `showSidebar` property which should be reactive and could be used in templates. This is the reason why the store is placed inside a mixin.

Regarding your second question about vuex, I realized that although vuex is good no doubts but I was using it only for the sidebar. Isolating the sidebar makes it a bit more re-usable and package independent.  Since I had in plan to build other templates, it was easier to simply add the sidebar plugin folder rather than install vuex, add the actions and so on.

For learning, I would also suggest https://github.com/cristijora/vue-light-bootstrap-dashboard a more recent repo which has pretty much the same structure but some refined parts like this sidebar which is also possible do declare in templates https://github.com/cristijora/vue-light-bootstrap-dashboard/blob/master/src/components/Dashboard/Layout/DashboardLayout.vue#L5

**Comment by fakefarm** [comment]
Ah, I didn't realize the reactive nature of `mixin`. I think  hot module reload was giving me the impression that it was reactive. Thank you for the thorough explanations. 

I will most certainly review the other project you linked to. Thank you for the guidance!

**Comment by fakefarm** [comment]
I ended up creating a step-by-step gist ([How to create a Vue Plugin Component](https://gist.github.com/fakefarm/c8bc710fc258268c29617473be47d2c0)) to document what I learned from reviewing `SidebarPlugin`. If it wouldn't be too much trouble, would you mind reading it over and letting me know if I missed anything? (It's short 😄 )

**Comment by cristijora** [comment]
Overall I think it's a very nice guide and pretty straight forward for every dev regardless of experience. If you want to get a bit more into details there are some additional things like
1. Auto install for browser usage (usually used by [npm packages](https://github.com/cristijora/vue-form-wizard/blob/master/src/index.js#L14) ) 
2. Specifying [installation options](https://github.com/cristijora/vue-notifyjs/blob/master/src/index.js#L67) also [here](https://github.com/ElemeFE/element/blob/dev/src/index.js#L157) or even installing other plugins.

The possibilities here are pretty much endless since you have access to the Vue object and the vue instance. You could even access vuex, get installation options from local storage 

All this is really options. Just to let you know that there are many possibilities. I think mentioning about installation options would be sufficient for your gist. Overall I think it's a nice guide. The official guide also provides some insight https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin
