### ISSUE TITLE
Difference of syntax for import

### ISSUE THREAD

**Issue by sylvaincaillot** [cristijora/vue-paper-dashboard#26]
Hello,
Just need some clarifications of why you are using different syntaxes for importing components from element-ui.

For example, for the forms, you are using:
```
 import {DatePicker, TimeSelect, Slider, Tag, Input, Button, Select, Option} from 'element-ui'
export default {
    components: {
      [DatePicker.name]: DatePicker,
      [TimeSelect.name]: TimeSelect,
      [Slider.name]: Slider,
      [Tag.name]: Tag,
      [Input.name]: Input,
      [Button.name]: Button,
      [Option.name]: Option,
      [Select.name]: Select
    }}
```

While for the panels, you are using:
```
import Vue from 'vue'
import {Collapse, CollapseItem} from 'element-ui'

 Vue.use(Collapse)
 Vue.use(CollapseItem)
 export default {
   ...
  }
```

Is there a good reason for that? Is ist necessary to declare a Import Vue in the second case?

thank you for your help

Sylvain

**Comment by cristijora** [comment]
Hi again @sylvaincaillot

There is no reason for having different import syntax. I will unify the import syntax in the next update to use the first option probably.
The difference between them is that the 1st option has local component declaration while the second one has global component declaration.

Although the 1st one is more verbose it's usually the preferred one since you can optimize your bundle and improve your website performance by importing pages async with webpack. 

The second one allows you to use certain components globally. In case you have components which are used in many places (Button for example) you could use the second approach and do that in your entry file (main.js, App.vue)

**Comment by sylvaincaillot** [comment]
Thank you @cristijora for youe email.

I have effectivelly moved all the global declarations (Vue.use() and Vue.Component() such as standard Element-UI components) into the main.js. I am then using the extra bits from Element-UI locally as you recommend to optimize the performance.

Thank you again for your great PRO template, it is really good in term of best practices for a newbie using Vuejs. I will need to explore authentication and Vuex now, perhaps it could be part of an other template one day.

Cheers

S.
