### ISSUE TITLE
Pagination css and Vue-Data-tables

### ISSUE THREAD

**Issue by sylvaincaillot** [cristijora/vue-paper-dashboard#27]
Hello,

i am using the https://github.com/njleonzhang/vue-data-tables plugin to display data from the server. It's pretty neat and uses Element-Ui as well.

However, i really like your look and feel for the pagination (Paginated tables example) and would like to apply it to my datatables. Would you have some directions to do so as it uses el-pagination and you seem to appreciate Element-UI as I do?

Thank you for your help

S.

**Comment by cristijora** [comment]
Hi @sylvaincaillot If i'm not mistaked I replied on email to this question.
If not, I do indeed like element-ui and the components it provides. As for vue-data-tables, it is a nice wrapper but I can't say it's very customizable since it doesn't have slots to replace the pagination for example. 

For such situations, I personally like using raw components from element or from the template and build the "data table" based on application requirements. Vue-data-tables is a wrapper in the end and you could easily build up something simillar quickly. Here is an example https://jsfiddle.net/usdhrcLa/29/

Based on this example you could replace the pagination with the one from the template as it has pretty much the same api.

If all this stuff seems too much "boilerplate" and extra work for you, you could simply customize the look of the element pagination. Here is a starting point https://jsfiddle.net/usdhrcLa/57/ In the template itself, you don't necessarily need to specify the colors manually since you can set element-ui colors via scss.

Hope this stuff helps :) Also as a side note I'd suggest opening issues related to PRO version here https://github.com/creativetimofficial/vue-paper-dashboard-pro/issues since that repo is related to the PRO version while this is the free version and people might get confused when searching certain issues here.

**Comment by sylvaincaillot** [comment]
Thank you very @cristijora for your help and your time. I am learning a lot. I will definitely try to set up my own wrapper when I will have more time. For the time being, I will use the css solution.

Thank you again
