### ISSUE TITLE
loaded section remains at its scroll pos

### ISSUE THREAD

**Issue by simondavies** [cristijora/vue-paper-dashboard#3]
Firstly, great little app.

Using your demo app, when I scroll the page content, then select another menu option, the page content loads, but if it will keep its scroll position.

EG: 
 I select the typography menu item, I then scroll down to view the page content.
I then select the icons menu item, when the page loads, it is positioned half way down the icons page.

Might need to add a page top functionality on load of page, so on switching menu/pages the user is presented with the top of that page each time?

Used on: 

Macbook Pro (macOS Sierra)
Chrome v58.0.3

**Comment by cristijora** [comment]
Thanks for posting the issue. Normally this could achieved [vue-router](https://router.vuejs.org/en/advanced/scroll-behavior.html) but for some reason it doesn't work probably because of how the content is arranged. Will look into it

**Comment by frohikey** [comment]
Vue router doesn't handle scroll positioning automatically. 
You can use this, but it does work only when you're in history mode and windows.scrollTo "works" (it depends on CSS)

```javascript
const router = new VueRouter({
  routes, // short for routes: routes
  linkActiveClass: 'active',
  mode: 'history'
  scrollBehavior (to, from, savedPosition) {    
    if (savedPosition) {
       return savedPosition
     } else {
       return { x: 0, y: 0 }
     }
   }
})
```

Unfortunately it doesn't work in our case. The reason is - side panel and main panel both have ``overflow: auto;`` and thus ``window.scrollTo`` does nothing.

I've fixed it by adding ``vue-scrollto`` plugin and resetting a scroll position when routing.

**Comment by cristijora** [comment]
I played around with this a bit and not quite sure whether this should be implemented at all. It feels more natural to have the scroll remain where it is. @alexandru-paduraru  what's your opinion about this? I see that the angular dashboards that you have on creative-time don't scroll to top when changing between pages.

**Comment by alexandru-paduraru** [comment]
@cristijora hmm... I think the best option would be to wait for some more feedback and then we will see what will be the final decision for this. 

If we will decide to do the scroll, I think we can easily fix it without any additional libraries, just from CSS. At this moment if you inspect element in chrome you will see that the `.main-panel` has a height of 100% with overflow: auto property. That means we are blocking the page to 100% of the screen and add a scroll inside of it. When you scroll in the main panel you are not moving at all the "body" of the page. 

I guess that the page remains there because vue cannot have control inside of the main-panel scroll. So I think that if we put the sidebar element with fixed position (not it is absolute in page) and remove the overflow and the height of the `.main-panel`, basically, we let the main panel be free when we scroll down the page. Then I think the vue will automatically move the page to the top of the body. Makes sense?

**Comment by cristijora** [comment]
The css has been changed according to @alexandru-paduraru suggestions. It's possible to use vue-router in history mode now and customize the desired scroll behavior via `scrollBehavior` function
